site_name: MC Status Docs

theme:
  name: readthedocs

markdown_extensions:
  - footnotes
  - admonition
  # - attr_list
  # - pymdownx.arithmatex
  # - pymdownx.superfences
  # - pymdownx.details
  # - pymdownx.magiclink
  # - pymdownx.tasklist:
  #     custom_checkbox: true
#  - pymdownx.emoji:
#      emoji_generator: !!python/name:pymdownx.emoji.to_svg

  - toc:
      permalink: true

plugins:
  - search
  - roamlinks 